[2024-06-30T13:18:36.598+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_sentiment_analysis.extract_load scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30T13:18:36.624+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_sentiment_analysis.extract_load scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30T13:18:36.625+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-06-30T13:18:36.683+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_load> on 2024-06-29 00:00:00+00:00
[2024-06-30T13:18:36.709+0000] {standard_task_runner.py:60} INFO - Started process 276 to run task
[2024-06-30T13:18:36.714+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_sentiment_analysis', 'extract_load', 'scheduled__2024-06-29T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/dag_sentiment_analysis.py', '--cfg-path', '/tmp/tmpnbfgznsx']
[2024-06-30T13:18:36.718+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask extract_load
[2024-06-30T13:18:36.811+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-30T13:18:36.898+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_sentiment_analysis.extract_load scheduled__2024-06-29T00:00:00+00:00 [running]> on host a9ab29ad88be
[2024-06-30T13:18:37.118+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='de-team' AIRFLOW_CTX_DAG_ID='dag_sentiment_analysis' AIRFLOW_CTX_TASK_ID='extract_load' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T00:00:00+00:00'
[2024-06-30T13:19:36.946+0000] {logging_mixin.py:188} INFO - SSL handshake failed: ac-mukte2i-shard-00-01.pn34g58.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1007) (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms),SSL handshake failed: ac-mukte2i-shard-00-00.pn34g58.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1007) (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms),SSL handshake failed: ac-mukte2i-shard-00-02.pn34g58.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1007) (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66815b4a83532abbffcb85f1, topology_type: Unknown, servers: [<ServerDescription ('ac-mukte2i-shard-00-00.pn34g58.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-mukte2i-shard-00-00.pn34g58.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1007) (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>, <ServerDescription ('ac-mukte2i-shard-00-01.pn34g58.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-mukte2i-shard-00-01.pn34g58.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1007) (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>, <ServerDescription ('ac-mukte2i-shard-00-02.pn34g58.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-mukte2i-shard-00-02.pn34g58.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1007) (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>
[2024-06-30T13:19:36.955+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/finnhub_mongodb_loader.py", line 7, in extract_load
    collection = mongodb_loader.load('news', 'finnhub_news')
  File "/opt/airflow/plugins/mongodb_loader.py", line 29, in load
    db = mongo_client[database]
TypeError: 'NoneType' object is not subscriptable
[2024-06-30T13:19:37.007+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dag_sentiment_analysis, task_id=extract_load, execution_date=20240629T000000, start_date=20240630T131836, end_date=20240630T131937
[2024-06-30T13:19:37.066+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task extract_load ('NoneType' object is not subscriptable; 276)
[2024-06-30T13:19:37.119+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-30T13:19:37.195+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30T14:20:31.422+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_sentiment_analysis.extract_load scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30T14:20:31.435+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_sentiment_analysis.extract_load scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30T14:20:31.436+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-06-30T14:20:31.453+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_load> on 2024-06-29 00:00:00+00:00
[2024-06-30T14:20:31.464+0000] {standard_task_runner.py:60} INFO - Started process 311 to run task
[2024-06-30T14:20:31.467+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_sentiment_analysis', 'extract_load', 'scheduled__2024-06-29T00:00:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dag_sentiment_analysis.py', '--cfg-path', '/tmp/tmpvj7ao2bl']
[2024-06-30T14:20:31.469+0000] {standard_task_runner.py:88} INFO - Job 69: Subtask extract_load
[2024-06-30T14:20:31.485+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-30T14:20:31.525+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_sentiment_analysis.extract_load scheduled__2024-06-29T00:00:00+00:00 [running]> on host 7c9851f56a65
[2024-06-30T14:20:31.609+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='de-team' AIRFLOW_CTX_DAG_ID='dag_sentiment_analysis' AIRFLOW_CTX_TASK_ID='extract_load' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T00:00:00+00:00'
[2024-06-30T14:20:34.545+0000] {logging_mixin.py:188} INFO - Pinged your deployment. You successfully connected to MongoDB!
[2024-06-30T14:20:36.133+0000] {logging_mixin.py:188} INFO - Successfully load news to MongoDB
[2024-06-30T14:20:36.134+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-06-30T14:20:36.146+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=dag_sentiment_analysis, task_id=extract_load, execution_date=20240629T000000, start_date=20240630T142031, end_date=20240630T142036
[2024-06-30T14:20:36.189+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-06-30T14:20:36.212+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
