[2024-06-30T13:27:40.499+0000] {scheduler_job_runner.py:780} ERROR - Executor reports task instance <TaskInstance: dag_sentiment_analysis.extract_load scheduled__2024-06-29T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
