[2024-06-30T13:32:45.653+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_sentiment_analysis.extract_load scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30T13:32:45.696+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_sentiment_analysis.extract_load scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-06-30T13:32:45.697+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-06-30T13:32:45.761+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_load> on 2024-06-29 00:00:00+00:00
[2024-06-30T13:32:45.792+0000] {standard_task_runner.py:60} INFO - Started process 490 to run task
[2024-06-30T13:32:45.837+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_sentiment_analysis', 'extract_load', 'scheduled__2024-06-29T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dag_sentiment_analysis.py', '--cfg-path', '/tmp/tmpwn0toicj']
[2024-06-30T13:32:45.885+0000] {standard_task_runner.py:88} INFO - Job 52: Subtask extract_load
[2024-06-30T13:32:46.156+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-30T13:32:46.600+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_sentiment_analysis.extract_load scheduled__2024-06-29T00:00:00+00:00 [running]> on host a9ab29ad88be
[2024-06-30T13:32:47.087+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='de-team' AIRFLOW_CTX_DAG_ID='dag_sentiment_analysis' AIRFLOW_CTX_TASK_ID='extract_load' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T00:00:00+00:00'
[2024-06-30T13:33:51.642+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-06-30T13:33:51.671+0000] {process_utils.py:131} INFO - Sending 15 to group 490. PIDs of all processes in the group: [490]
[2024-06-30T13:33:51.673+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 490
[2024-06-30T13:33:51.674+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-30T13:33:51.676+0000] {logging_mixin.py:188} INFO - Task received SIGTERM signal
[2024-06-30T13:33:51.678+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/finnhub_mongodb_loader.py", line 7, in extract_load
    collection = mongodb_loader.load('news', 'finnhub_news')
  File "/opt/airflow/plugins/mongodb_loader.py", line 29, in load
    db = mongo_client[database]
TypeError: 'NoneType' object is not subscriptable
[2024-06-30T13:33:51.703+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_sentiment_analysis, task_id=extract_load, execution_date=20240629T000000, start_date=20240630T133245, end_date=20240630T133351
[2024-06-30T13:33:51.738+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 52 for task extract_load ('NoneType' object is not subscriptable; 490)
[2024-06-30T13:33:51.767+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=490, status='terminated', exitcode=1, started='13:32:44') (490) terminated with exit code 1
