[2024-06-30T14:09:30.339+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_sentiment_analysis.extract_load scheduled__2024-06-30T13:00:00+00:00 [queued]>
[2024-06-30T14:09:30.349+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_sentiment_analysis.extract_load scheduled__2024-06-30T13:00:00+00:00 [queued]>
[2024-06-30T14:09:30.349+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-06-30T14:09:30.368+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_load> on 2024-06-30 13:00:00+00:00
[2024-06-30T14:09:30.383+0000] {standard_task_runner.py:60} INFO - Started process 200 to run task
[2024-06-30T14:09:30.385+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_sentiment_analysis', 'extract_load', 'scheduled__2024-06-30T13:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/dag_sentiment_analysis.py', '--cfg-path', '/tmp/tmp4y61t6ld']
[2024-06-30T14:09:30.388+0000] {standard_task_runner.py:88} INFO - Job 66: Subtask extract_load
[2024-06-30T14:09:30.410+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-30T14:09:30.454+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_sentiment_analysis.extract_load scheduled__2024-06-30T13:00:00+00:00 [running]> on host 7c9851f56a65
[2024-06-30T14:09:30.549+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='de-team' AIRFLOW_CTX_DAG_ID='dag_sentiment_analysis' AIRFLOW_CTX_TASK_ID='extract_load' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-30T13:00:00+00:00'
[2024-06-30T14:09:54.233+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/finnhub_mongodb_loader.py", line 7, in extract_load
    collection = mongodb_loader.load('news', 'finnhub_news')
  File "/opt/airflow/plugins/mongodb_loader.py", line 26, in load
    mongo_client = get_mongo_client(mongo_uri)
  File "/opt/airflow/plugins/mongodb_loader.py", line 8, in get_mongo_client
    client = pymongo.MongoClient(mongo_uri)
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 774, in __init__
    res = uri_parser.parse_uri(
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/uri_parser.py", line 543, in parse_uri
    dns_options = dns_resolver.get_options()
  File "/home/airflow/.local/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 99, in get_options
    raise ConfigurationError(str(exc)) from None
pymongo.errors.ConfigurationError: The resolution lifetime expired after 21.122 seconds: Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.
[2024-06-30T14:09:54.263+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dag_sentiment_analysis, task_id=extract_load, execution_date=20240630T130000, start_date=20240630T140930, end_date=20240630T140954
[2024-06-30T14:09:54.292+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 66 for task extract_load (The resolution lifetime expired after 21.122 seconds: Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.; Server Do53:127.0.0.11@53 answered The DNS operation timed out.; 200)
[2024-06-30T14:09:54.337+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-30T14:09:54.360+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
